### ISSUE TITLE
Unable to connect to PostgreSQL server: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by carera** [clue/docker-adminer#12]
Hi,
when trying to connect to a postgres server using provided adminer, i get the following message:

Unable to connect to PostgreSQL server: fe_sendauth: no password supplied

The user I am loggin in with DOES have a password and works from other postgres clients (works also from locally running apache-hosted adminer)

**Comment by clue** [comment]
Thanks for posting @carera.

Personally, I haven't used this to access PostgreSQL in a while.

Is this still relevant? Does anybody else encounter this issue?

**Comment by mathroc** [comment]
connectiong to PostgreSQL servers works fine here

**Comment by clue** [comment]
Thanks for the confirmation @mathroc!

**Comment by tlapicka** [comment]
I add `hostssl` record in pg_hba.conf and problem is solved.

    # IPv4 local connections:
    host    all             all             127.0.0.1/32            md5
    hostssl all             all             127.0.0.1/32            md5
    # IPv6 local connections:
    host    all             all             ::1/128                 md5
    hostssl all             all             ::1/128                 md5
