### ISSUE TITLE
Pass signals to supervisord to support stopping cleanly

### ISSUE THREAD

**Issue by mtirsel** [clue/docker-adminer#17]
Current form of CMD does not passes signals to the supervisord and container can not be stopped via standard `docker stop` command. After a timeout, container is killed by Docker.

**Comment by mikehaertl** [comment]
@clue As there's no further progress on the alpine PRs, could we at least fix this? It's annoying that the container takes so long to shut down. All you'd have to do is to use `tini` instead of supervisor.

**Comment by clue** [comment]
Thanks for posting, see #18 for a possible fix.

**Comment by clue** [comment]
> All you'd have to do is to use `tini` instead of supervisor.

I'd be happy to review this in case anybody feels like filing a PR :+1:

**Comment by mikehaertl** [comment]
@clue  I've not used tini myself. Just found it being used in the PR for alpine. So if #18 fixes this problem here, I'm fine.

**Comment by clue** [comment]
Closed via #18
