### ISSUE TITLE
No license provided - can we use it?

### ISSUE THREAD

**Issue by FRosner** [clue/docker-adminer#23]
Hi!

I can't find any software license attached to this project. I would like to use / modify it. Under which conditions is this possible?

Thanks

**Comment by clue** [comment]
Thanks for pointing this out!

As far as my work is involved, everything is released under the permissive [MIT license](https://opensource.org/licenses/MIT).

Please be aware that this image may reference other software that uses a different license though.

**Comment by FRosner** [comment]
Understood @clue. I just wanted to check if I can safely modify your code (which is the Dockerfile + conf files) and under which conditions.
